name:                Golang
version:             0.1.0.0
github:              "KarasssDev/golang-interpreter"
license:             BSD3
author:              "Karasev Viktor"
maintainer:          "karasssdev@gmail.com"
copyright:           "2022 Karasev Viktor"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/KarasssDev/golang-interpreter/README.md>

dependencies:
- base >= 4.7 && < 5
- hspec
- mtl
- containers
- array
- parsec

library:
  source-dirs: 
  - src 
  - src/interpreter
  - src/parser

executables:
  Golang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall 
    - -Wcompat 
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns 
    - -Wredundant-constraints
    dependencies:
    - Golang

# tests:
#   Golang-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - Golang
