#!/bin/sh 

cd demos
tests=`find . -type f -name "*.go"`
stack build

for test in $tests
do
    go    run $test &> expected
    stack run $test &> actual
    dif=`diff expected actual`

    if [[ $? == 0 ]] ; then
        echo "Test $test done"
    else
        echo "Test $test failed"
        echo $dif
        exit 1
    fi

done

rm expected actual
exit 0