name: Build & Test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'golang-dev'

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Build package
        run: |
          stack build 

      - name: Run tests
        run: |
          ./demos/runTest


