name: Build & Test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'golang-dev'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '9.2.2' 
          enable-stack: true
          stack-version: '2.7.5'
      - run: stack build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.10.7' 
          enable-stack: true
          stack-version: 'latest'
      - run: ./demos/runTest

